const vm = Vue.createApp({
    data(){
        return {
            arr: [
              { Name: 'John', Surname: 'Smith', Birthyear: 1990, City: 'New York', Occupation: 'Engineer' },
              { Name: 'Anna', Surname: 'Doe', Birthyear: 1991, City: 'Los Angeles', Occupation: 'Teacher' },
              { Name: 'Michael', Surname: 'Brown', Birthyear: 1985, City: 'Chicago', Occupation: 'Doctor' },
              { Name: 'Emily', Surname: 'Clark', Birthyear: 1992, City: 'Houston', Occupation: 'Nurse' },
              { Name: 'David', Surname: 'Johnson', Birthyear: 1988, City: 'Phoenix', Occupation: 'Lawyer' },
              { Name: 'Sophia', Surname: 'White', Birthyear: 1993, City: 'Philadelphia', Occupation: 'Artist' },
              { Name: 'Daniel', Surname: 'Jones', Birthyear: 1990, City: 'San Antonio', Occupation: 'Architect' },
              { Name: 'Olivia', Surname: 'Miller', Birthyear: 1995, City: 'San Diego', Occupation: 'Designer' },
              { Name: 'Matthew', Surname: 'Wilson', Birthyear: 1989, City: 'Dallas', Occupation: 'Chef' },
              { Name: 'Emma', Surname: 'Taylor', Birthyear: 1992, City: 'San Jose', Occupation: 'Photographer' },
              { Name: 'James', Surname: 'Anderson', Birthyear: 1991, City: 'Austin', Occupation: 'Developer' },
              { Name: 'Isabella', Surname: 'Thomas', Birthyear: 1994, City: 'Jacksonville', Occupation: 'Musician' },
              { Name: 'Liam', Surname: 'Martinez', Birthyear: 1987, City: 'San Francisco', Occupation: 'Writer' },
              { Name: 'Mia', Surname: 'Garcia', Birthyear: 1993, City: 'Columbus', Occupation: 'Journalist' },
              { Name: 'William', Surname: 'Lopez', Birthyear: 1986, City: 'Fort Worth', Occupation: 'Pilot' },
              { Name: 'Alex', Surname: 'Davis', Birthyear: 1988, City: 'Charlotte', Occupation: 'Accountant' },
              { Name: 'Grace', Surname: 'Martinez', Birthyear: 1995, City: 'Detroit', Occupation: 'Artist' },
              { Name: 'Aiden', Surname: 'Robinson', Birthyear: 1992, City: 'Memphis', Occupation: 'Photographer' },
              { Name: 'Chloe', Surname: 'Clark', Birthyear: 1990, City: 'Seattle', Occupation: 'Nurse' },
              { Name: 'Jack', Surname: 'Rodriguez', Birthyear: 1985, City: 'Denver', Occupation: 'Engineer' },
              { Name: 'Ella', Surname: 'Lewis', Birthyear: 1993, City: 'El Paso', Occupation: 'Teacher' },
              { Name: 'Henry', Surname: 'Walker', Birthyear: 1991, City: 'Boston', Occupation: 'Doctor' },
              { Name: 'Lily', Surname: 'Hall', Birthyear: 1994, City: 'Nashville', Occupation: 'Lawyer' },
              { Name: 'Oscar', Surname: 'Allen', Birthyear: 1989, City: 'Oklahoma City', Occupation: 'Architect' },
              { Name: 'Sophie', Surname: 'Young', Birthyear: 1995, City: 'Las Vegas', Occupation: 'Designer' },
              { Name: 'Benjamin', Surname: 'Hernandez', Birthyear: 1987, City: 'Louisville', Occupation: 'Chef' },
              { Name: 'Amelia', Surname: 'King', Birthyear: 1992, City: 'Baltimore', Occupation: 'Journalist' },
              { Name: 'Lucas', Surname: 'Scott', Birthyear: 1988, City: 'Milwaukee', Occupation: 'Pilot' },
              { Name: 'Zoe', Surname: 'Green', Birthyear: 1986, City: 'Albuquerque', Occupation: 'Musician' },
              { Name: 'Nathan', Surname: 'Baker', Birthyear: 1990, City: 'Tucson', Occupation: 'Developer' },
              { Name: 'Victoria', Surname: 'Carter', Birthyear: 1991, City: 'Fresno', Occupation: 'Artist' },
              { Name: 'Oliver', Surname: 'Perez', Birthyear: 1989, City: 'Sacramento', Occupation: 'Writer' },
              { Name: 'Harper', Surname: 'Rivera', Birthyear: 1985, City: 'Mesa', Occupation: 'Engineer' },
              { Name: 'Ethan', Surname: 'Campbell', Birthyear: 1988, City: 'Kansas City', Occupation: 'Teacher' },
              { Name: 'Ava', Surname: 'Gonzalez', Birthyear: 1993, City: 'Atlanta', Occupation: 'Lawyer' },
              { Name: 'Mason', Surname: 'Wright', Birthyear: 1987, City: 'Colorado Springs', Occupation: 'Photographer' },
              { Name: 'Hannah', Surname: 'Mitchell', Birthyear: 1992, City: 'Raleigh', Occupation: 'Doctor' },
              { Name: 'Samuel', Surname: 'Hill', Birthyear: 1991, City: 'Omaha', Occupation: 'Developer' },
              { Name: 'Emily', Surname: 'Moore', Birthyear: 1990, City: 'Miami', Occupation: 'Journalist' },
              { Name: 'Adam', Surname: 'Thomas', Birthyear: 1985, City: 'Long Beach', Occupation: 'Nurse' },
              { Name: 'Megan', Surname: 'Jackson', Birthyear: 1989, City: 'Virginia Beach', Occupation: 'Chef' },
              { Name: 'Dylan', Surname: 'Harris', Birthyear: 1995, City: 'Oakland', Occupation: 'Pilot' },
              { Name: 'Lucy', Surname: 'Martinez', Birthyear: 1994, City: 'Minneapolis', Occupation: 'Musician' },
              { Name: 'Ryan', Surname: 'Clark', Birthyear: 1986, City: 'Tulsa', Occupation: 'Engineer' },
              { Name: 'Samantha', Surname: 'Robinson', Birthyear: 1992, City: 'Arlington', Occupation: 'Teacher' },
              { Name: 'Isaac', Surname: 'White', Birthyear: 1988, City: 'Tampa', Occupation: 'Lawyer' },
              { Name: 'Jessica', Surname: 'Lewis', Birthyear: 1985, City: 'New Orleans', Occupation: 'Designer' },
              { Name: 'Noah', Surname: 'Walker', Birthyear: 1993, City: 'Bakersfield', Occupation: 'Developer' },
              { Name: 'Sofia', Surname: 'Perez', Birthyear: 1991, City: 'Honolulu', Occupation: 'Photographer' },
              { Name: 'Sebastian', Surname: 'Hall', Birthyear: 1994, City: 'Anaheim', Occupation: 'Journalist' },
              { Name: 'Ashley', Surname: 'King', Birthyear: 1989, City: 'Aurora', Occupation: 'Pilot' },
              { Name: 'Caleb', Surname: 'Scott', Birthyear: 1995, City: 'Santa Ana', Occupation: 'Artist' },
              { Name: 'Emily', Surname: 'Davis', Birthyear: 1987, City: 'Riverside', Occupation: 'Writer' },
              { Name: 'Logan', Surname: 'Rodriguez', Birthyear: 1986, City: 'Stockton', Occupation: 'Doctor' },
              { Name: 'Victoria', Surname: 'Martinez', Birthyear: 1990, City: 'St. Louis', Occupation: 'Engineer' },
              { Name: 'Owen', Surname: 'Young', Birthyear: 1991, City: 'Cincinnati', Occupation: 'Teacher' },
            ]
          }          
    },
    methods: {
      deleteRow(index) {
        this.arr.splice(index, 1);
      }
    }
}).mount("#app")